---
- name: Install Nginx on all web servers
  hosts: webservers
  become: yes

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Copy HTML file
      copy:
        src: index.html
        dest: /var/www/html/index.html
        mode: '0644'

    - name: Start and enable Nginx
      systemd:
        name: nginx
        state: started
        enabled: yes